title: Brahmic Engine
description: Documentation for the Brahmic Engine, a Telugu to Python transpiler.
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
